//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoundBoard.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoundBoard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Sound Board.
        /// </summary>
        internal static string AboutSoundBoard {
            get {
                return ResourceManager.GetString("AboutSoundBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust volume.
        /// </summary>
        internal static string AdjustVolume {
            get {
                return ResourceManager.GetString("AdjustVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All sounds cleared from &apos;{0}&apos;..
        /// </summary>
        internal static string AllSoundsClearedFromTab {
            get {
                return ResourceManager.GetString("AllSoundsClearedFromTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Files.
        /// </summary>
        internal static string AudioFiles {
            get {
                return ResourceManager.GetString("AudioFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button layout was changed..
        /// </summary>
        internal static string ButtonLayoutWasChanged {
            get {
                return ResourceManager.GetString("ButtonLayoutWasChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change button grid....
        /// </summary>
        internal static string ChangeButtonGrid {
            get {
                return ResourceManager.GetString("ChangeButtonGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        internal static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose sound.
        /// </summary>
        internal static string ChooseSound {
            get {
                return ResourceManager.GetString("ChooseSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all sounds.
        /// </summary>
        internal static string ClearAllSounds {
            get {
                return ResourceManager.GetString("ClearAllSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear configuration.
        /// </summary>
        internal static string ClearConfiguration {
            get {
                return ResourceManager.GetString("ClearConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Files.
        /// </summary>
        internal static string ConfigurationFiles {
            get {
                return ResourceManager.GetString("ConfigurationFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration was cleared..
        /// </summary>
        internal static string ConfigurationWasCleared {
            get {
                return ResourceManager.GetString("ConfigurationWasCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration was imported..
        /// </summary>
        internal static string ConfigurationWasImported {
            get {
                return ResourceManager.GetString("ConfigurationWasImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this page?.
        /// </summary>
        internal static string ConfirmDeletePage {
            get {
                return ResourceManager.GetString("ConfirmDeletePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by Micah Morrison.
        /// </summary>
        internal static string CreatedByMicahMorrison {
            get {
                return ResourceManager.GetString("CreatedByMicahMorrison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag a sound here....
        /// </summary>
        internal static string DragASoundHere {
            get {
                return ResourceManager.GetString("DragASoundHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export configuration.
        /// </summary>
        internal static string ExportConfiguration {
            get {
                return ResourceManager.GetString("ExportConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; doesn&apos;t seem to exist!.
        /// </summary>
        internal static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to sound.
        /// </summary>
        internal static string GoToSound {
            get {
                return ResourceManager.GetString("GoToSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How does it work?.
        /// </summary>
        internal static string HowDoesItWork {
            get {
                return ResourceManager.GetString("HowDoesItWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import configuration.
        /// </summary>
        internal static string ImportConfiguration {
            get {
                return ResourceManager.GetString("ImportConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop.
        /// </summary>
        internal static string Loop {
            get {
                return ResourceManager.GetString("Loop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework Error.
        /// </summary>
        internal static string NetFrameworkError {
            get {
                return ResourceManager.GetString("NetFrameworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Page.
        /// </summary>
        internal static string NewPage {
            get {
                return ResourceManager.GetString("NewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops!.
        /// </summary>
        internal static string Oops {
            get {
                return ResourceManager.GetString("Oops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set color.
        /// </summary>
        internal static string SetColor {
            get {
                return ResourceManager.GetString("SetColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...an app where you can create and run your own custom sound board full of your favorite bytes, effects, and clips..
        /// </summary>
        internal static string SoundBoardDescription {
            get {
                return ResourceManager.GetString("SoundBoardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Board is split into pages, so you can group your favorite sounds together. To get started, add your first sound page by clicking &quot;add page&quot; above!.
        /// </summary>
        internal static string SoundBoardExplanation1 {
            get {
                return ResourceManager.GetString("SoundBoardExplanation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To load a sound, just drag an audio file onto a button or click the three little dots to browse. Then click the button with the sound name on it to play it!.
        /// </summary>
        internal static string SoundBoardExplanation2 {
            get {
                return ResourceManager.GetString("SoundBoardExplanation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To find a sound in a hurry, just start typing its name and an instant search bar will appear!.
        /// </summary>
        internal static string SoundBoardExplanation3 {
            get {
                return ResourceManager.GetString("SoundBoardExplanation3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages and sounds are saved, so when you&apos;re done, just close the app, and it&apos;ll pick up right where you left off next time!.
        /// </summary>
        internal static string SoundBoardExplanation4 {
            get {
                return ResourceManager.GetString("SoundBoardExplanation4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add, remove pages, or rename pages at any time by clicking buttons at the top. Feel free to remove this page when you&apos;re ready to go! Bring it back any time by clicking &quot;help&quot;..
        /// </summary>
        internal static string SoundBoardExplanation5 {
            get {
                return ResourceManager.GetString("SoundBoardExplanation5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sound is set to loop.
        /// </summary>
        internal static string SoundSetToLoop {
            get {
                return ResourceManager.GetString("SoundSetToLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound &apos;{0}&apos; was cleared..
        /// </summary>
        internal static string SoundWasCleared {
            get {
                return ResourceManager.GetString("SoundWasCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only .wav and .mp3 files supported..
        /// </summary>
        internal static string SupportedFileTypes {
            get {
                return ResourceManager.GetString("SupportedFileTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page &apos;{0}&apos; was removed..
        /// </summary>
        internal static string TabWasRemoved {
            get {
                return ResourceManager.GetString("TabWasRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required .NET Framework Version ({0}) is not currently installed..
        /// </summary>
        internal static string TargetFrameworkNotInstalled {
            get {
                return ResourceManager.GetString("TargetFrameworkNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem!.
        /// </summary>
        internal static string ThereWasAProblem {
            get {
                return ResourceManager.GetString("ThereWasAProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uh oh!.
        /// </summary>
        internal static string UhOh {
            get {
                return ResourceManager.GetString("UhOh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string VersionNumber {
            get {
                return ResourceManager.GetString("VersionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The volume of this sound is offset by {0}.
        /// </summary>
        internal static string VolumeOfSoundIsOffset {
            get {
                return ResourceManager.GetString("VolumeOfSoundIsOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Sound Board!.
        /// </summary>
        internal static string WelcomeToSoundBoard {
            get {
                return ResourceManager.GetString("WelcomeToSoundBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want to call it?.
        /// </summary>
        internal static string WhatDoYouWantToCallIt {
            get {
                return ResourceManager.GetString("WhatDoYouWantToCallIt", resourceCulture);
            }
        }
    }
}
